In [1]:
# Code 1

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
url = 'https://www.imdb.com/list/ls024149810/'
r = requests.get(url)
soup = BeautifulSoup(r.content, 'html.parser')

In [4]:
movie_title = []
for title in soup.findAll('h3', {'class' : 'lister-item-header'}):
    titles = title.find('a', href = True).get_text()
    movie_title.append(titles)

In [5]:
genre_list = []
for genre in soup.findAll('span', {'class' : 'genre'}):
    genre = genre.get_text()
    genre_list.append(genre.strip())

In [6]:
topmovies = pd.DataFrame({'Movie Title' : movie_title, 'Genre' : genre_list})
print(topmovies)

                                          Movie Title  \
0                            The Shawshank Redemption   
1                                       The Godfather   
2                                        Citizen Kane   
3                                        12 Angry Men   
4                                    Schindler's List   
5                      The Good, the Bad and the Ugly   
6      Star Wars: Episode V - The Empire Strikes Back   
7       The Lord of the Rings: The Return of the King   
8                                     The Dark Knight   
9                              The Godfather: Part II   
10                                       Pulp Fiction   
11                                         Fight Club   
12                                             Psycho   
13                              2001: A Space Odyssey   
14                                         Metropolis   
15                 Star Wars: Episode IV - A New Hope   
16  The Lord of the Rings: The 

In [7]:
# Code 2

In [8]:
import pandas as pd

In [9]:
data = pd.read_csv('weight-height.csv')

In [10]:
data.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [11]:
data.head(10)

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801
5   Male  67.253016  152.212156
6   Male  68.785081  183.927889
7   Male  68.348516  167.971110
8   Male  67.018950  175.929440
9   Male  63.456494  156.399676

In [12]:
data.describe()

Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [13]:
left = pd.DataFrame({"Key": [0, 1], "Data_A": ["a", "b"]})
right = pd.DataFrame({"Key": [1, 2, 3], "Data_B": [2, 2, 2]})
result = pd.merge(left, right, on="Key", how="outer", indicator=True)
print(result)

   Key Data_A  Data_B      _merge
0    0      a     NaN   left_only
1    1      b     2.0        both
2    2    NaN     2.0  right_only
3    3    NaN     2.0  right_only


In [14]:
# Code 3

In [15]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /Users/zhezhou/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [16]:
sents = 'I love her. But, she does not love me. Sad story!'
nltk.sent_tokenize(sents)

['I love her.', 'But, she does not love me.', 'Sad story!']

In [17]:
# Code 4

In [18]:
import numpy as np

In [19]:
A = np.array([[2, 3], [2, 2]])
print(A)
B = np.linalg.inv(A)
print(B)
result = np.dot(A, B)
print(result)

[[2 3]
 [2 2]]
[[-1.   1.5]
 [ 1.  -1. ]]
[[1. 0.]
 [0. 1.]]


In [20]:
C = np.array([[1, 2], [3, 4]])
print(C)
D = np.array([[5, 6], [7, 8]])
print(D)
matrix_multiply = np.dot(C, D)
print(matrix_multiply)
hadamard_product = C * D
print(hadamard_product)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
